### ISSUE TITLE
[Error] json: cannot unmarshal number

### ISSUE THREAD

**Issue by olajoshal** [vasilyukvasiliy/cemelon#3]
Block index:  256818 [Error] json: cannot unmarshal number -1703168784 into Go struct field Tx.ver of type uint64

Block index:  124724 [Error] json: cannot unmarshal number -1 into Go struct field Block.fee of type uint64

How can i resolve these errors?

Thank you

**Comment by xorcare** [comment]
Hi! This issue occurs because of errors in the package blockchain (https://git.io/v5dN0). The problem fixed now works correctly.

**Comment by xorcare** [comment]
Also to fix the error, you need to locally update the package: github.com/vasilyukvasiliy/blockchain
Command:
```
go get -u github.com/vasilyukvasiliy/blockchain
```

**Comment by olajoshal** [comment]
Thank you!
After I updated the package, the previously mentioned blocks were parsed successfully.
Unfortunately there are similar error messages:
Block index:  337877 [Error] json: cannot unmarshal number -1 into Go struct field Tx.lock_time of type uint64
Block index:  447402 [Error] json: cannot unmarshal number -2058925319 into Go struct field Tx.lock_time of type uint64

**Comment by xorcare** [comment]
Fixed bugs, if there are new write this!
